server {
    listen 80;
    server_name localhost;

    location ~ ^/(?:\.htpasswd|\.git) {
        deny all;
        return 403;
    }



    location /files/ {
        auth_basic           "Private configs";
        auth_basic_user_file /data/files/.htpasswd;

        rewrite ^/files(/.*)$ $1 break;

        root /data/files/$remote_user;

        try_files $uri $uri/ =404;
        default_type application/json;
        add_header Content-Type application/json always;
    }

    location / {
        return 403;
    }
}