server {
    listen 80;
    server_name localhost;
    root /data/files;

    location ~ ^/(?:\.htpasswd|\.git) {
        deny all;
        return 403;
    }

    location / {
        autoindex off;
        auth_basic "files";
        auth_basic_user_file /data/files/.htpassws;

        try_files /$remote_user/$uri =404;

        default_type application/json;
        types { } default_type application/json;
        add_header Content-Type application/json always;
    }

    location / {
        return 403;
    }
}