server {
    listen 80;
    server_name localhost;

    location /files/ {
        root /files
        autoindex off;
        auth_basic "files";
        auth_basic_user_file /files/repo/.htpassws;

        default_type application/json;
        add_header Content-Type application/json always;
        try_files /configs/$remote_user/$uri =404;;
    }

    location / {
        return 403;
    }
}